// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmVVmDCePDye5-Lv7jorINe6tlLbkAHYQ',
    appId: '1:950897918709:web:72e178b3453f1f408bbbbc',
    messagingSenderId: '950897918709',
    projectId: 'registration-form-flutte-74c5d',
    authDomain: 'registration-form-flutte-74c5d.firebaseapp.com',
    storageBucket: 'registration-form-flutte-74c5d.firebasestorage.app',
    measurementId: 'G-718KR093EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIum3rpUKV9sOuQSUAoEWyTuhq_BBTj9o',
    appId: '1:950897918709:android:725db16914ef71308bbbbc',
    messagingSenderId: '950897918709',
    projectId: 'registration-form-flutte-74c5d',
    storageBucket: 'registration-form-flutte-74c5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUpte_UeMBxEYV2KAibL0JOSIeg4HJfgE',
    appId: '1:950897918709:ios:e927871a29fddbb98bbbbc',
    messagingSenderId: '950897918709',
    projectId: 'registration-form-flutte-74c5d',
    storageBucket: 'registration-form-flutte-74c5d.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUpte_UeMBxEYV2KAibL0JOSIeg4HJfgE',
    appId: '1:950897918709:ios:e927871a29fddbb98bbbbc',
    messagingSenderId: '950897918709',
    projectId: 'registration-form-flutte-74c5d',
    storageBucket: 'registration-form-flutte-74c5d.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmVVmDCePDye5-Lv7jorINe6tlLbkAHYQ',
    appId: '1:950897918709:web:b231cd772f8f5c218bbbbc',
    messagingSenderId: '950897918709',
    projectId: 'registration-form-flutte-74c5d',
    authDomain: 'registration-form-flutte-74c5d.firebaseapp.com',
    storageBucket: 'registration-form-flutte-74c5d.firebasestorage.app',
    measurementId: 'G-N1665HJQ7M',
  );
}
